### ISSUE TITLE
Questions about Prime Natives - Account Lifetime

### ISSUE THREAD

**Issue by crashzk** [SomethingFromSomewhere/Prime-Natives#2]
I would like to know if this plugin it checks the player's steam / csgo account time, or if it checks the prime status time the player has.

**Comment by SomethingFromSomewhere** [comment]
@paulocrash account creation time. Requires public client's profile. (Only for no Prime clients)

**Comment by crashzk** [comment]
> @paulocrash account creation time. Requires public client's profile. (Only for no Prime clients)

@SomethingFromSomewhere I think I get it, so I believe there is a BUG.

Has a player that has a steam account for two months, activated Status Prime in CSGO for two days, but still he can not enter the server.

CVAR set it as follows `sm_prime_natives_account_lifetime_minimum_days "25"`

Even then it can't login, if I disable this plugin it can already login, or if I slow down to less than two days in CVAR it can login already.

**[EDIT]**
He has the public client profile;
